name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run every day at midnight UTC

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . WebCrawler --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . WebCrawler --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run WebCrawler folder 
      run: |
        python WebCrawler/web_crawler.py

